### ISSUE TITLE
MD to YML conversion drops links

### ISSUE THREAD

**Issue by baranga** [release-notes/release-notes-cli#22]
Given this `CHANGELOG.md`:
```md
# changelog
description

## [Unreleased]
### Added
- new [stuff]

[Unreleased]: https//example.com/unreleased
[stuff]: https//example.com/stuff
```

I get for `release-notes convert CHANGELOG.md -t yml` this:
```yml
title: changelog
description: description
releases:
  - version: Unreleased
    added:
      - 'new [stuff]'
```
As one can see the links are missing.

The spec says neither defines how to handle links nor which property/tags supports markdown. A possible solution could be to make all descriptive fields markdown in the spec and convert to something like this:
```yml
title: changelog
description: description
releases:
  - version: '[Unreleased](https://example.com/unreleased)'
    added:
      - 'new [stuff](https://example.com/stuff)'
```
